title: Kris Carta's personal blog
description: Personal Site and Blog
author: Kris Carta
author-tagline: Hi, I'm Kris
github: https://github.com/kcarta
about: I'm a software manager and developer, and this is my space for exploring thoughts on *everything* to do with modern (agile) software delivery, from management to technology. Have a comment? Hit me up on LinkedIn!

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/kriscarta"
    - icon: fa-github
      link: "https://github.com/kcarta"

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://www.kriscarta.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: GFM
plugins:
  - jekyll-paginate
  - jekyll-gist

collections:
  posts:
    permalink: /:collection/:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']