title: Kris Carta's personal blog
description: Personal Site and Blog
author: Kris Carta
author-tagline: Hi, I'm Kris
github: https://github.com/kcarta
about: I'm a software nerd, and this is my space for exploring *everything* from tech to leadership. Have a comment? Hit me up on social media!

enableTags: true
tagarray: []

future: true

social:
    - icon: fa-brands fa-linkedin
      link: "https://www.linkedin.com/in/kriscarta"
    - icon: fa-brands fa-github
      link: "https://github.com/kcarta"
    - icon: fa-brands fa-bluesky
      link: "https://bsky.app/profile/krc22.bsky.social"

urls:
    - text: About
      url: /about/
    - text: Now
      url: /now/
    - text: XML Feed
      url: /feed.xml

url: "https://www.kriscarta.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: GFM
plugins:
  - jekyll-paginate
  - jekyll-gist

collections:
  posts:
    permalink: /:collection/:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']