title: Kris Carta's personal blog
description: Personal Site and Blog
author: Kris Carta
author-tagline: Hi, I'm Kris
github: https://github.com/kcarta
about: I'm a software manager and developer, and this is my space for exploring thoughts on *everything* to do with modern (agile) software delivery, from management to technology

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/kriscarta"
    - icon: fa-github
      link: "https://github.com/kcarta"

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://www.kriscarta.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: GFM
plugins:
  - jekyll-paginate
  - jekyll-gist

collections:
  posts:
    permalink: /:collection/:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://kcarta-github-pages-comments.herokuapp.com/v2/entry/kcarta/kcarta.github.io/master/comments

reCaptcha:
  siteKey: 6Ld2TXYqAAAAALr6lZw5grz_2THLC5dJGM7JP5LQ